local function Plug( )
print("---TFA Weapon Holsters---")
print("Updated to Weapon Holstering v0.1c")
print("Changelog:")
print("- Version .1B->.1C")
print("- Support for TFA Day of Defeat/TFA Day of Infamy added.")
print("- Fix for Main Pack Pistols implemented.")
print("- Support for TFA Call of Duty 4 added")
print("- Support for Randomly picked Non-Pack SWEPs")
print("Note: Star Wars weapons in the works. -Servius")
print("---TFA Weapon Holsters---")
end
hook.Add("PlayerInitialSpawn", "Updates", Plug)